### ISSUE TITLE
demo url is not working http://fullstack-demo.herokuapp.com/

### ISSUE THREAD

**Issue by gugwad** [DaftMonk/fullstack-demo#27]
This demo url is not working. It throws application error.
The error message as follows. 

`An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details.`

**Comment by kawashimaken** [comment]
I have the following experience:
FAILED CASE(now):
I also experiencing the same issue when I try to deploy my app to heroku. 
generator-angular-fullstack v2.1.1+ node v5.0.0

SUCCEEDED CASE(past):
I once succeeded in deploying another app to heroku with v2.1.1, + node 0.12.x) 

I am not sure if it has something to do with the node version.
now, when I run 
`yo angular-fullstack:heroku`
It can not proceed successfully. It returns:
`Push rejected, no Cedar-supported app detected`
My guess is that heroku side has had some updates.

**Comment by kawashimaken** [comment]
Now I can successfully init heroku by running 

```
grunt build
grunt buildcontrol:heroku
```

without the error I mentioned above.
I guess the reason is that I was trying to init heroku without fixing some module dependency errors.
However I have got the problem as mentioned here 
https://github.com/DaftMonk/generator-angular-fullstack/issues/152#issuecomment-161985312
please give it a look, any suggestions are welcome.  Thank you in advance.

**Comment by drandreaskrueger** [comment]
same here

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

http://fullstack-demo.herokuapp.com/

**Comment by Awk34** [comment]
It's not maintained anymore

**Comment by drandreaskrueger** [comment]
thx.

suggest to put that into README.md
